### ISSUE TITLE
Add default loading.gif

### ISSUE THREAD

**Issue by dmolineus** [ebrelsford/Leaflet.loading#21]
It would be nice if a default loading gif is provided. To support spin.js as well, you could use the `:empty` selector:

```css
.leaflet-control-loading:empty {
    background-image: url('loading.gif');
}
```
